### ISSUE TITLE
Facebook login fails when facebook app is installed

### ISSUE THREAD

**Issue by ghonche-yqr** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#67] opened 2021-05-12 13:23 UTC
Hi
I'm facing this error when trying to login using facebook with android device:

> facebook login error: there is an error in logging you into this application

I figured out this happens only when the [facebook app](https://play.google.com/store/apps/details?id=com.facebook.katana) is installed! It seems to be a common problem due to [this issue](https://forum.ionicframework.com/t/ionic-4-failed-facebook-login-with-android-when-the-native-facebook-app-is-installed/184950).
I have installed this plugin recently (before I used to use **cordova-plugin-facebook4** and this didn't happen).
any way, I'm not sure if this is a bug related to the facebook app or facebook-connect plugin but it will be a big help if you take a look.

**Comment by hjfigueira** [comment] 2021-05-12 14:51
The same is thing is happening to me.

**Comment by noahcooper** [comment] 2021-05-13 11:05
I cannot reproduce this issue. Can you try logging in with a Facebook account that is an app administrator? You should get a more detailed error message. I wonder if perhaps the key hash you entered on https://developers.facebook.com is not correct.

**Comment by hjfigueira** [comment] 2021-05-13 14:12
It worked! Thanks and sorry for bothering you with such a common issue. I was using the web setup on firebase and haven't configured for android when I moved to native login. Now it's working fine.

Thanks once again.

**Comment by noahcooper** [comment] 2021-08-17 00:42
Closing this issue, but feel free to open a new issue if you continue to encounter problems.

**Closed by noahcooper** 2021-08-17 00:42 UTC
